config/routes.rb
Rails.application.routes.draw do
  # root 'pins#index'
  resources :pins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/pin.rb
class Pin < ApplicationRecord
    # has_one_attached :image
    has_many_attached :images do |attachable|
        attachable.variant :small, resize_to_limit: [100, 100]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
    skip_before_action :verify_authenticity_token
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = Pin.new(pin_params)
    respond_to do |format|
      if @pin.save
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:title, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveStoragePractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin) do |form| %>
  <% if pin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

<br/>
<div>
  <%= form.label :images %>
  <br/>
  <%= form.file_field :images, multiple: true %>
</div>
<br/>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="<%= dom_id pin %>">
  <p>
    <strong>Title:</strong>
    <%= pin.title %>
  </p>

  <%#= pin.image %>

</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Show this pin", @pin %> |
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pins</h1>

<div id="pins">
  <% @pins.each do |pin| %>
    <%= render pin %>
    <p>
      <%= link_to "Show this pin", pin %>
    </p>
  <% end %>
</div>

<%= link_to "New pin", new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/show.html.erb
<p style="color: green"><%= notice %></p>



<div>
<% @pin.images.each do |im| %>
  <% if im.present? %>
    <%= image_tag im.representation(resize_to_limit: [150, 150])%>
  <% end %>
<% end %>


  <%= link_to "Edit this pin", edit_pin_path(@pin) %> |
  <%= link_to "Back to pins", pins_path %>

  <%= button_to "Destroy this pin", @pin, method: :delete %>
</div>